version: '3.9'

services:
  es01:
    container_name: es_container_1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es01
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    ports:
      - 9200:9200

  es02:
    container_name: es_container_2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es02
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net

  es03:
    container_name: es_container_3
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es03
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    
  kibana:
    container_name: kb_container
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge

# FIXME: add peristent volumes