version: '3.9'

services:
  mongodb0:
    container_name: mongodb0
    image: mongo:5.0.5
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./data0/mongodb:/data/db # For persisting data to host
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb1:
    container_name: mongodb1
    image: mongo:5.0.5
    expose:
      - 27017
    volumes:
      - ./data1/mongodb:/data/db # For persisting data to host
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb2:
    container_name: mongodb2
    image: mongo:5.0.5
    expose:
      - 27017
    volumes:
      - ./data2/mongodb:/data/db # For persisting data to host
    entrypoint: ["/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
