version: '3.9'

services:
  es00:
    container_name: es_container_0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es00
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es00,es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - ./data/es00/:/usr/share/elasticsearch/data:rw
    healthcheck:
      test: curl http://127.0.0.1:9200/_cat/health
      interval: 5s
      timeout: 10s
      retries: 5

  es01:
    container_name: es_container_1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es02
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es00,es03
      - cluster.initial_master_nodes=es00,es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    volumes:
      - ./data/es01/:/usr/share/elasticsearch/data:rw
    healthcheck:
      test: curl http://127.0.0.1:9200/_cat/health
      interval: 5s
      timeout: 10s
      retries: 5

  es02:
    container_name: es_container_2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - node.name=es03
      - cluster.name=es-docker-cluster
      - xpack.security.enabled=false
      - discovery.seed_hosts=es00,es03
      - cluster.initial_master_nodes=es00,es01,es02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    volumes:
      - ./data/es02/:/usr/share/elasticsearch/data:rw
    healthcheck:
      test: curl http://127.0.0.1:9200/_cat/health
      interval: 5s
      timeout: 10s
      retries: 5

  kibana:
    container_name: kb_container
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es00:9200","http://es01:9200","http://es02:9200"]'
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge
